# Generated by Django 4.2.4 on 2023-08-31 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_wallets', models.ManyToManyField(related_name='recorded_wallets', to='transactions.wallet', verbose_name='recorded wallet list')),
            ],
        ),
    ]
