# Generated by Django 4.2.4 on 2023-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_currencyrates_ratio_alter_transaction_amount'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='recorded_wallets',
            field=models.ManyToManyField(related_name='recorded_wallets', to='transactions.wallet'),
        ),
    ]
