# Generated by Django 4.2.4 on 2023-09-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
