# Generated by Django 4.2.4 on 2023-09-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='CMT', max_length=3),
        ),
    ]
