# Generated by Django 4.2.4 on 2023-09-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_currencyrates_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyrates',
            unique_together={('from_currency', 'to_currency')},
        ),
    ]
