# Generated by Django 4.2.4 on 2023-09-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_currencyrates_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrates',
            name='ratio',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
